-- Migration 011: Demo bootstrap
-- REMOVED: Demo API key seeding moved to packages/demo/api/src/seed.ts
-- The original migration inserted a hardcoded global-admin API key, which is a
-- security risk in production. The demo key is now minted at seed time and never
-- committed; demo data is seeded via the demo seed script only.
