import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const packagesDir = path.resolve(here, "../../..");

/** Workspace packages that projects generated by @stratum-hq/create install from the registry. */
const GENERATED_APP_PACKAGES = ["lib", "core", "sdk", "db-adapters"];

/**
 * Returns the workspace versions of those packages that the npm registry does
 * not serve yet. A version PR raises them before the release publishes them,
 * so an install of a generated project cannot succeed until then.
 */
export function unpublishedStratumVersions(): string[] {
  const missing: string[] = [];
  for (const dir of GENERATED_APP_PACKAGES) {
    const pkg = JSON.parse(fs.readFileSync(path.join(packagesDir, dir, "package.json"), "utf8")) as {
      name: string;
      version: string;
    };
    const spec = `${pkg.name}@${pkg.version}`;
    const res = spawnSync("npm", ["view", spec, "version"], { encoding: "utf8" });
    if (res.status !== 0 || res.stdout.trim() !== pkg.version) missing.push(spec);
  }
  return missing;
}
